default_config:

logger:
  default: info
  logs:
    custom_components.blebox_shutterbox_tilt: debug
# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:
